### ISSUE TITLE
config doesn't work .

### ISSUE THREAD

**Issue by nillerusr** [Chatur27/Eureka-kernel-for-SM-A105-Q#2]
Hello, after changing something in config through menuconfig kernel won't boot.

**Comment by nillerusr** [comment]
`make defconfig` creates defconfig from temporary config. Again, defconfig should not manually edited

**Comment by Chatur27** [comment]
> `make savedefconfig` creates defconfig from temporary config. Again, defconfig should not be manually edited.
> 
> retarded

Go read that sentence well.
It said "it is not recommended" which means u can edit directly.
Linux dev said that because there are noobs like you out there who is going to mess the kernel !

I'm doing kernel development since 1 year and I never got any issue. So please, keep your retarded lessons for yourself 😂

**Comment by neel0210** [comment]
> `make savedefconfig` creates defconfig from temporary config. Again, defconfig should not be manually edited.
> 
> retarded

Man, this doesn't look professional, it's his choice how he wants to compile so stop it.

**Comment by nillerusr** [comment]
> this doesn't look professional

also applies to Chatur
